version: '3'
services:
    client:
        container_name: client
        environment:
         - ROS_HOSTNAME=client
         - ROS_MASTER_URI=http://172.18.0.1:11311
        image: ros_image:1.0
        ports:
         - 8083:8080
        stdin_open: true
        tty: true
